name: "Backup Notion Workspace"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run backup script
        run: npm install && npm run backup
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
          NOTION_USER_ID: ${{ secrets.NOTION_USER_ID }}
          APPEND_MODE: ${{ secrets.APPEND_MODE }}

      - name: Checkout backup repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO_USERNAME }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}
          path: "backup-repo"

      - name: Conditionally handle files based on APPEND_MODE
        env:
          REPO_EMAIL: ${{ secrets.REPO_EMAIL }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          APPEND_MODE: ${{ secrets.APPEND_MODE }}
        run: |
          cd backup-repo
          
          # Complete replacement if APPEND_MODE is false or not given
          if [ "$APPEND_MODE" != "true" ]; then
            echo "Performing complete replacement..."
            find . -type f ! -name 'index.html' ! -name 'readme.md' -delete
            find . -type d ! -path . ! -path './.github*' -exec rm -rf {} +
          else
            echo "Appending files..."
          fi
          
          # Use rsync to copy new files, always excluding certain files
          rsync -av --exclude='.github' --exclude='index.html' --exclude='readme.md' ../workspace/ ./
          
          git config --local user.email "${REPO_EMAIL}"
          git config --local user.name "${REPO_USERNAME}"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated Notion workspace backup"
          git push