name: "Backup Notion Workspace"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run backup script
        run: npm install && npm run backup
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
          NOTION_USER_ID: ${{ secrets.NOTION_USER_ID }}
          APPEND_MODE: ${{ secrets.APPEND_MODE }}

      - name: Checkout backup repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO_USERNAME }}/${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_PERSONAL_ACCESS_TOKEN }}
          path: "backup-repo"
      - name: Check for global .gitignore and list its contents
        run: |
          GLOBAL_GITIGNORE=$(git config --global core.excludesfile)
          if [ -z "$GLOBAL_GITIGNORE" ]; then
            echo "No global .gitignore file set."
          else
            if [ -f "$GLOBAL_GITIGNORE" ]; then
              echo "Global .gitignore file located at: $GLOBAL_GITIGNORE"
              cat "$GLOBAL_GITIGNORE"
            else
              echo "Global .gitignore file is set to $GLOBAL_GITIGNORE, but the file does not exist or cannot be read."
            fi
          fi
      - name: List .gitignore in the repository and .git/info/exclude
        run: |
          echo "Listing .gitignore files in repository:"
          find . -name .gitignore -exec echo {} \; -exec cat {} \;
          echo "Contents of .git/info/exclude:"
          cat .git/info/exclude || echo ".git/info/exclude does not exist."
      - name: Commit changes to backup repo
        env:
          REPO_EMAIL: ${{ secrets.REPO_EMAIL }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          APPEND_MODE: ${{ secrets.APPEND_MODE }}
        run: |
          cd backup-repo
          
          # ----- CURRENT DIR - backup-repo -------

          # Check APPEND_MODE; perform complete replacement if false or not given
          if [ "$APPEND_MODE" != "true" ]; then
            echo "Listing contents of checked out backup-repo directory (BEFORE DELETION):"
            ls -al
            echo "Performing complete replacement..."
            # Delete files for complete replacement mode
            find . -type f ! -name 'index.html' ! -name 'readme.md' ! -name '.git*' -exec rm -f {} + 2>/dev/null
            find . -type d ! -path . ! -path './.github*' ! -path './.git*' -exec rm -rf {} + 2>/dev/null
          else
            echo "Using APPEND_MODE..."
          fi

          echo "Listing contents of backup-repo directory (BEFORE COPY):"
          ls -al

          # ----- CURRENT DIR - backup-repo -------

          # copy new files, allowing exclusion as needed
          #rsync -av --exclude='.github' --exclude='index.html' --exclude='readme.md' ../workspace/ ./
          echo "Copying from temporary workspaceDir to backup-repo folder..."
          cp -a ../workspace/. .
          echo "Listing contents of the backup-repo (AFTER COPY)"
          ls -al

          git config --local user.email "${REPO_EMAIL}"
          git config --local user.name "${REPO_USERNAME}"

          echo "Ignored files:"
          git status --ignored
          git check-ignore -v .

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "Automated Notion workspace backup"
          git push
